---
- name: Httpd and php configuration
  hosts: stapp01
  become: yes
  tasks:
    - name: Install httpd and php packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - httpd
        - php
    - name: Insert document root path in apache
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '/var/www/html'
        replace: '/var/www/html/myroot'
    - name: Create a myroot dir
      file:
        path: /var/www/html/myroot
        state: directory
        mode: 0755    
    - name: Copy file to myroot
      copy:
        src: /home/thor/playbooks/templates/phpinfo.php.j2
        dest: /var/www/html/myroot/phpinfo.php
        owner: apache
        group: apache
    - name: httpd service enalbe and start
      service:
        name: httpd
        enabled: true
        state: started
        