---
- name: Create an empty file 
  hosts: all
  become: yes
  vars:
    host_info:
      - hostname: stapp01
        path: /usr/src/code.txt
        owner: tony
        group: tony
        mode: 0744
      - hostname: stapp02
        path: /usr/src/code.txt
        owner: steve
        group: steve
        mode: 0744
      - hostname: stapp03
        path: /usr/src/code.txt
        owner: banner
        group: banner
        mode: 0744
  tasks:
    - name: Create an empty file
      ansible.builtin.file:
        path: "{{item.path}}"
        state: touch
        owner: "{{item.owner}}"
        group: "{{item.group}}"
        mode: "{{item.mode}}"
      loop: "{{host_info}}"
      when: inventory_hostname == item.hostname

#stapp01 ansible_connection=ssh ansible_host=172.16.238.10 ansible_ssh_user=tony ansible_ssh_pass=Ir0nM@n
#stapp02 ansible_connection=ssh ansible_host=172.16.238.11 ansible_ssh_user=steve ansible_ssh_pass=Am3ric@
#stapp03 ansible_connection=ssh ansible_host=172.16.238.12 ansible_ssh_user=banner ansible_ssh_pass=BigGr33n

    
