---
- hosts: stapp01
  become: yes
  become_user: root
  roles:
    - role/httpd

========================

index.html.j2
/home/thor/ansible/role/httpd/templates/
This file was created using Ansible on {{ inventory_hostname }}
=========================

thor@jump_host ~/ansible/role/httpd/tasks$ cat main.yml 
---
# tasks file for role/test

- name: install the latest version of HTTPD
  yum:
    name: httpd
    state: latest

- name: Start service httpd
  service:
    name: httpd
    state: started

- name: Copy index.html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644