---
- hosts: all
  become: yes
  tasks:
    - name:
      archive:
        path: /usr/src/dba/
        dest: /opt/dba/apps.tar.gz
        format: gz
        force_archive: true
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"